apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: interview-lab
data:
  default.conf: |
    server {
      listen 8080;

      location / {
          proxy_pass http://backend:8080;
      }
    }